zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    owners-service:
      path: /owners/**
      url: forward:/customer/owners
    gateway-owners-service:
      path: /gateway/owners/**
      url: forward:/customer/owners
    # app requests GET and POST to https://pet-clinic.*.com/api/gateway/owners/7
    # and it needs to be transformed into https://pet-clinic.*.com/api/customer/owners
    customers-service: /customer/**
    api-gateway: /gateway/**
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  messages:
    basename: messages/messages # Internationalization
  zipkin:
    baseUrl: http://tracing-server:80 #orig: 9411

management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://tracing-server:80/api/v2/spans #orig: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:80/eureka/ #orig: 8761