zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  messages:
    basename: messages/messages # Internationalization
  zipkin:
    baseUrl: http://tracing-server:9411

management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/