server:
  port: 8081

spring:
  zipkin:
    baseUrl: http://tracing-server:9411
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}?sslmode=verify-full&sslrootcert=DigiCertGlobalRootCA.crt.pem
    username: ${SPRING_DATASOURCE_USERNAME}
    azure.passwordless-enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_DATASOURCE_SHOW_SQL}
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
